import type { WorkStreamPresentationFacts, WorkStreamPresentationState, StatusRole } from '../status-presentation'
import type { WorkBucket } from '../live-activity'

/** One contract consumed by shared, Core serialization and web badge tests. */
export interface PresentationCase {
  name: string
  facts: WorkStreamPresentationFacts
  state: WorkStreamPresentationState
  role: Exclude<StatusRole, 'attention'>
  attention: boolean
  bucket: WorkBucket
  label: string
}
const active = { status: 'active', openWaits: [] } as const
const paused = { id: 'pause', pausedAt: '2026-09-21T00:00:00Z', reason: null, parkAt: null, agentIds: [] }
export const WORK_STREAM_PRESENTATION_CASES: PresentationCase[] = [
  {
    name: 'true idle',
    facts: active,
    state: 'idle',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Idle',
  },
  {
    name: 'running',
    facts: { ...active, derivedState: 'in_progress' },
    state: 'in_progress',
    role: 'progress',
    attention: false,
    bucket: 'running',
    label: 'In Progress',
  },
  {
    name: 'failed execution',
    facts: { ...active, derivedState: 'execution_failed' },
    state: 'execution_failed',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Execution Failed',
  },
  {
    name: 'queued',
    facts: { status: 'queued', openWaits: [] },
    state: 'queued',
    role: 'queue',
    attention: false,
    bucket: 'queued',
    label: 'Queued',
  },
  {
    name: 'review wait',
    facts: { ...active, openWaits: [{ type: 'review' }] },
    state: 'in_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'In Review',
  },
  {
    name: 'question wait',
    facts: { ...active, openWaits: [{ type: 'question' }] },
    state: 'waiting_on_answer',
    role: 'humanWait',
    attention: true,
    bucket: 'needsYou',
    label: 'Waiting on Answer',
  },
  {
    name: 'manual blocker',
    facts: { ...active, openWaits: [{ type: 'manual' }] },
    state: 'blocked',
    role: 'danger',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'dependency',
    facts: { ...active, openWaits: [{ type: 'dependency' }] },
    state: 'waiting_on_dependency',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Waiting on Dependency',
  },
  {
    name: 'delivery approval',
    facts: { ...active, delivery: { kind: 'approval' } },
    state: 'delivery_approval',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Approve Delivery',
  },
  {
    name: 'human PR review',
    facts: { ...active, delivery: { kind: 'review' } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    // The #362 wire shape: pr-auto-merge, GitHub requires an approval, no waits,
    // and the legacy derived vocabulary still says waiting_on_dependency.
    name: 'required human PR review under auto-merge',
    facts: { ...active, derivedState: 'waiting_on_dependency', delivery: { kind: 'review' } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    name: 'required human PR review for payloads omitting waits',
    facts: { status: 'active', derivedState: 'waiting_on_dependency', delivery: { kind: 'review' } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    name: 'human PR merge',
    facts: { ...active, delivery: { kind: 'merge' } },
    state: 'delivery_merge',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Merge Pull Request',
  },
  {
    name: 'automatic CI or unknown provider',
    facts: { ...active, delivery: { kind: 'external' } },
    state: 'delivery_external',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Awaiting Code Host',
  },
  {
    name: 'delivery setup missing',
    facts: { ...active, delivery: { kind: 'setup' } },
    state: 'delivery_setup',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Delivery Setup Required',
  },
  {
    name: 'delivery failed',
    facts: { ...active, delivery: { kind: 'failure' } },
    state: 'delivery_failure',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Delivery Changes Required',
  },
  {
    name: 'paused',
    facts: { ...active, pause: paused },
    state: 'paused',
    role: 'neutral',
    attention: false,
    bucket: 'paused',
    label: 'Paused',
  },
  {
    name: 'paused with waits and delivery',
    facts: { ...active, pause: paused, openWaits: [{ type: 'manual' }], delivery: { kind: 'merge' } },
    state: 'paused',
    role: 'neutral',
    attention: false,
    bucket: 'paused',
    label: 'Paused',
  },
  {
    name: 'terminal beats pause and wait',
    facts: { status: 'done', pause: paused, openWaits: [{ type: 'review' }], delivery: { kind: 'merge' } },
    state: 'done',
    role: 'success',
    attention: false,
    bucket: 'queued',
    label: 'Done',
  },
  {
    name: 'canceled beats pause',
    facts: { status: 'canceled', pause: paused, openWaits: [{ type: 'review' }] },
    state: 'canceled',
    role: 'neutral',
    attention: false,
    bucket: 'queued',
    label: 'Canceled',
  },
  {
    name: 'explicit wait beats delivery',
    facts: { ...active, openWaits: [{ type: 'manual' }], delivery: { kind: 'merge' } },
    state: 'blocked',
    role: 'danger',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'empty waits erase stale review',
    facts: { ...active, derivedState: 'in_review' },
    state: 'idle',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Idle',
  },
  {
    name: 'legacy omitted review waits',
    facts: { status: 'active', derivedState: 'in_review' },
    state: 'in_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'In Review',
  },
  {
    name: 'legacy omitted manual waits',
    facts: { status: 'active', derivedState: 'blocked' },
    state: 'blocked',
    role: 'danger',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
]
