import type { WorkStreamPresentationFacts, WorkStreamPresentationState, StatusRole } from '../status-presentation'
import type { WorkBucket } from '../live-activity'

/** The actor's pre-rename name; nothing shipped with it, so it is an unknown value (human). */
const PRE_RENAME_ACTOR = 'manager'

/** One contract consumed by shared, Core serialization and web badge tests. */
export interface PresentationCase {
  name: string
  facts: WorkStreamPresentationFacts
  state: WorkStreamPresentationState
  role: StatusRole
  attention: boolean
  bucket: WorkBucket
  label: string
}
const active = { status: 'active', openWaits: [] } as const
const paused = { id: 'pause', pausedAt: '2026-09-21T00:00:00Z', reason: null, parkAt: null, agentIds: [] }
export const WORK_STREAM_PRESENTATION_CASES: PresentationCase[] = [
  {
    name: 'idle waiting for a slot',
    facts: { ...active, hasActiveSlotWait: true },
    state: 'waiting_for_slot',
    role: 'queue',
    attention: false,
    bucket: 'externalWait',
    label: 'Waiting for slot',
  },
  {
    name: 'running with secondary slot context',
    facts: { ...active, derivedState: 'in_progress', hasActiveSlotWait: true },
    state: 'in_progress',
    role: 'progress',
    attention: false,
    bucket: 'running',
    label: 'In Progress',
  },
  {
    name: 'true idle',
    facts: active,
    state: 'idle',
    role: 'neutral',
    attention: false,
    bucket: 'blocked',
    label: 'Idle',
  },
  {
    name: 'running',
    facts: { ...active, derivedState: 'in_progress' },
    state: 'in_progress',
    role: 'progress',
    attention: false,
    bucket: 'running',
    label: 'In Progress',
  },
  {
    name: 'failed execution',
    facts: { ...active, derivedState: 'execution_failed' },
    state: 'execution_failed',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Execution Failed',
  },
  {
    name: 'queued',
    facts: { status: 'queued', openWaits: [] },
    state: 'queued',
    role: 'queue',
    attention: false,
    bucket: 'queued',
    label: 'Queued',
  },
  {
    name: 'review wait',
    facts: { ...active, openWaits: [{ type: 'review' }] },
    state: 'in_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'In Review',
  },
  {
    name: 'question wait',
    facts: { ...active, openWaits: [{ type: 'question' }] },
    state: 'waiting_on_answer',
    role: 'humanWait',
    attention: true,
    bucket: 'needsYou',
    label: 'Waiting on Answer',
  },
  {
    name: 'manual blocker',
    facts: { ...active, openWaits: [{ type: 'manual' }] },
    state: 'blocked',
    role: 'attention',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'human-actor manual blocker',
    facts: { ...active, openWaits: [{ type: 'manual', actor: 'human' }] },
    state: 'blocked',
    role: 'attention',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'owner-actor manual wait',
    facts: { ...active, openWaits: [{ type: 'manual', actor: 'owner' }] },
    state: 'waiting_on_owner',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Waiting on Owner',
  },
  {
    name: 'unknown actor (including manager) is human',
    facts: { ...active, openWaits: [{ type: 'manual', actor: PRE_RENAME_ACTOR }] },
    state: 'blocked',
    role: 'attention',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'human manual wait outranks owner manual wait',
    facts: {
      ...active,
      openWaits: [
        { type: 'manual', actor: 'owner' },
        { type: 'manual', actor: 'human' },
      ],
    },
    state: 'blocked',
    role: 'attention',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'question outranks owner manual wait',
    facts: { ...active, openWaits: [{ type: 'manual', actor: 'owner' }, { type: 'question' }] },
    state: 'waiting_on_answer',
    role: 'humanWait',
    attention: true,
    bucket: 'needsYou',
    label: 'Waiting on Answer',
  },
  {
    name: 'owner manual wait beats delivery',
    facts: { ...active, openWaits: [{ type: 'manual', actor: 'owner' }], delivery: { kind: 'merge' } },
    state: 'waiting_on_owner',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Waiting on Owner',
  },
  {
    name: 'dependency',
    facts: { ...active, openWaits: [{ type: 'dependency' }] },
    state: 'waiting_on_dependency',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Waiting on Dependency',
  },
  {
    name: 'delivery approval',
    facts: { ...active, delivery: { kind: 'approval' } },
    state: 'delivery_approval',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Approve Delivery',
  },
  {
    name: 'human PR review',
    facts: { ...active, delivery: { kind: 'review' } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    // The #362 wire shape: pr-auto-merge, GitHub requires an approval, no waits,
    // and the legacy derived vocabulary still says waiting_on_dependency.
    name: 'required human PR review under auto-merge',
    facts: { ...active, derivedState: 'waiting_on_dependency', delivery: { kind: 'review' } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    name: 'required human PR review for payloads omitting waits',
    facts: { status: 'active', derivedState: 'waiting_on_dependency', delivery: { kind: 'review' } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    name: 'human PR merge',
    facts: { ...active, delivery: { kind: 'merge' } },
    state: 'delivery_merge',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Merge Pull Request',
  },
  {
    name: 'automatic CI or unknown provider',
    facts: { ...active, delivery: { kind: 'external' } },
    state: 'delivery_external',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Awaiting Code Host',
  },
  {
    name: 'delivery setup missing',
    facts: { ...active, delivery: { kind: 'setup' } },
    state: 'delivery_setup',
    role: 'attention',
    attention: false,
    bucket: 'blocked',
    label: 'Delivery Setup Required',
  },
  {
    name: 'delivery failed',
    facts: { ...active, delivery: { kind: 'failure' } },
    state: 'delivery_failure',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Delivery Changes Required',
  },
  {
    name: 'paused',
    facts: { ...active, pause: paused },
    state: 'paused',
    role: 'neutral',
    attention: false,
    bucket: 'paused',
    label: 'Paused',
  },
  {
    name: 'paused with waits and delivery',
    facts: { ...active, pause: paused, openWaits: [{ type: 'manual' }], delivery: { kind: 'merge' } },
    state: 'paused',
    role: 'neutral',
    attention: false,
    bucket: 'paused',
    label: 'Paused',
  },
  {
    name: 'terminal beats pause and wait',
    facts: { status: 'done', pause: paused, openWaits: [{ type: 'review' }], delivery: { kind: 'merge' } },
    state: 'done',
    role: 'success',
    attention: false,
    bucket: 'queued',
    label: 'Done',
  },
  {
    name: 'canceled beats pause',
    facts: { status: 'canceled', pause: paused, openWaits: [{ type: 'review' }] },
    state: 'canceled',
    role: 'neutral',
    attention: false,
    bucket: 'queued',
    label: 'Canceled',
  },
  {
    name: 'explicit wait beats delivery',
    facts: { ...active, openWaits: [{ type: 'manual' }], delivery: { kind: 'merge' } },
    state: 'blocked',
    role: 'attention',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
  {
    name: 'empty waits erase stale review',
    facts: { ...active, derivedState: 'in_review' },
    state: 'idle',
    role: 'neutral',
    attention: false,
    bucket: 'blocked',
    label: 'Idle',
  },
  {
    name: 'legacy omitted review waits',
    facts: { status: 'active', derivedState: 'in_review' },
    state: 'in_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'In Review',
  },
  {
    name: 'legacy omitted manual waits',
    facts: { status: 'active', derivedState: 'blocked' },
    state: 'blocked',
    role: 'attention',
    attention: true,
    bucket: 'needsYou',
    label: 'Blocked',
  },
]

/** Additive wire contract for native row adapters; aggregate vocabulary stays unchanged. */
export const CODE_HOST_DELIVERY_PRESENTATION_CASES: PresentationCase[] = [
  ...(
    [
      ['ci-pending', 'Awaiting CI'],
      ['draft', 'PR is draft'],
      ['awaiting-merge', 'Awaiting merge'],
      ['merged', 'PR merged — finalizing delivery'],
    ] as const
  ).map(([codeHostReason, label]) => ({
    name: `external ${codeHostReason}`,
    facts: { ...active, delivery: { kind: 'external' as const, explanation: { codeHostReason } } },
    state: 'delivery_external' as const,
    role: 'externalWait' as const,
    attention: false,
    bucket: 'externalWait' as const,
    label,
  })),
  ...(
    [
      ['ci-failed', 'CI failed'],
      ['merge-conflict', 'Resolve merge conflicts'],
      ['changes-requested', 'Changes requested'],
      ['closed', 'PR closed without merging'],
    ] as const
  ).map(([codeHostReason, label]) => ({
    name: `failure ${codeHostReason}`,
    facts: { ...active, delivery: { kind: 'failure' as const, explanation: { codeHostReason } } },
    state: 'delivery_failure' as const,
    role: 'danger' as const,
    attention: false,
    bucket: 'blocked' as const,
    label,
  })),
  {
    name: 'review wins CI pending',
    facts: { ...active, delivery: { kind: 'review', explanation: { gates: { checksState: 'pending' } } } },
    state: 'delivery_review',
    role: 'review',
    attention: true,
    bucket: 'needsYou',
    label: 'Review Pull Request',
  },
  {
    name: 'open PR does not prove merge readiness',
    facts: {
      ...active,
      delivery: { kind: 'external', explanation: { pullRequests: [{ number: 42, state: 'open' }] } },
    },
    state: 'delivery_external',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Awaiting Code Host',
  },
  {
    name: 'generic blocked is not a conflict',
    facts: { ...active, delivery: { kind: 'external', explanation: { gates: { mergeState: 'blocked' } } } },
    state: 'delivery_external',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Awaiting Code Host',
  },
  {
    name: 'future reason fails soft',
    facts: {
      ...active,
      delivery: {
        kind: 'external',
        explanation: { codeHostReason: 'future-reason' as never, gates: { checksState: 'pending' } },
      },
    },
    state: 'delivery_external',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'Awaiting Code Host',
  },
  {
    name: 'incompatible reason fails soft',
    facts: { ...active, delivery: { kind: 'failure', explanation: { codeHostReason: 'awaiting-merge' } } },
    state: 'delivery_failure',
    role: 'danger',
    attention: false,
    bucket: 'blocked',
    label: 'Delivery Changes Required',
  },
  {
    name: 'other waits keep precedence over CI',
    facts: {
      ...active,
      openWaits: [{ type: 'question' }],
      delivery: { kind: 'external', explanation: { codeHostReason: 'ci-pending' } },
    },
    state: 'waiting_on_answer',
    role: 'humanWait',
    attention: true,
    bucket: 'needsYou',
    label: 'Waiting on Answer',
  },
  {
    name: 'all designated PRs merged',
    facts: {
      ...active,
      delivery: {
        kind: 'external',
        explanation: {
          codeHostReason: 'merged',
          pullRequests: [
            { number: 42, state: 'merged' },
            { number: 8, state: 'merged' },
          ],
        },
      },
    },
    state: 'delivery_external',
    role: 'externalWait',
    attention: false,
    bucket: 'externalWait',
    label: 'PRs merged — finalizing delivery',
  },
]
