import '../line/motion.css'
import './theme.css'
import type { FarmSkin } from '../types'
import { LineBadge } from '../line/sprites'
import {
  BlueprintAvatar,
  BlueprintCompost,
  BlueprintCrates,
  BlueprintDecor,
  BlueprintDefs,
  BlueprintFarmhouse,
  BlueprintGround,
  BlueprintHut,
  BlueprintMailbox,
  BlueprintPerson,
  BlueprintRack,
  BlueprintPlant,
  BlueprintPlot,
  BlueprintRobot,
  BlueprintSeedShed,
  BlueprintSign,
  BlueprintStand,
  BlueprintYard,
} from './sprites'

/** The farm as a drafting sheet: white line drawings on cyanotype blue, marked up in highlighter. */
export const blueprintSkin: FarmSkin = {
  id: 'blueprint',
  label: 'Blueprint',
  className: 'g-skin-blueprint',
  Defs: BlueprintDefs,
  Ground: BlueprintGround,
  YardBack: BlueprintYard,
  yardFront: () => [],
  Sign: BlueprintSign,
  PlotGround: BlueprintPlot,
  Plant: BlueprintPlant,
  // A ringed glyph on a stalk is already a drawing's detail callout.
  Badge: LineBadge,
  badgeLift: (plot) => (plot.state === 'review' ? -42 : -34),
  Robot: BlueprintRobot,
  Person: BlueprintPerson,
  Avatar: BlueprintAvatar,
  avatarViewBox: '-21 -52 42 42',
  Hut: BlueprintHut,
  Rack: BlueprintRack,
  Stand: BlueprintStand,
  Farmhouse: BlueprintFarmhouse,
  // Its door (i -0.18..0.18 on the wall at j 0.75) onto a porch 4px up, out to j 1.25.
  farmhouseDoor: { i: 0, j: 0.75, floor: 4, steps: [1.25, 1.3] },
  SeedShed: BlueprintSeedShed,
  Mailbox: BlueprintMailbox,
  Crates: BlueprintCrates,
  Compost: BlueprintCompost,
  Decor: BlueprintDecor,
  boxes: {
    robot: [-20, -54, 40, 60],
    person: [-16, -58, 32, 62],
    plant: [-26, -44, 52, 56],
    sign: [-150, -36, 160, 42],
    hut: [-44, -50, 96, 70],
    rack: [-28, -72, 56, 96],
    stand: [-44, -72, 88, 88],
    farmhouse: [-92, -104, 184, 150],
    seedShed: [-56, -58, 112, 90],
    mailbox: [-24, -62, 96, 76],
    crates: [-40, -40, 80, 56],
    compost: [-30, -26, 60, 44],
  },
  worldPad: { top: 90, side: 40, bottom: 60 },
}
