import { resolve } from 'node:path'
import { fnv1a } from '../src/theme/fnv'

/** Same hash, same two files, as vite.config.ts's computeBuiltinCssFingerprint
 * — see theme/builtinFingerprint.ts's doc comment for why. Computed
 * separately here (not imported from vite.config.ts) since this script is
 * bundled by Bun.build, not loaded through Vite. Exported so tests can
 * construct a snapshot the SHIPPED (bundled) flash script will actually
 * accept — a plain unbundled `import('./builtinFingerprint')` sees the
 * 'dev' fallback, not the real value baked into the bundle by this file. */
export async function computeBuiltinCssFingerprint(): Promise<string> {
  const indexCss = await Bun.file(resolve(import.meta.dir, '../src/index.css')).text()
  const builtinsCss = await Bun.file(resolve(import.meta.dir, '../src/theme/builtins.css')).text()
  return fnv1a(`${indexCss}\u0000${builtinsCss}`)
}

export async function generateThemeFlash() {
  const build = await Bun.build({
    entrypoints: [resolve(import.meta.dir, '../src/theme/flash.ts')],
    target: 'browser',
    format: 'iife',
    minify: true,
    define: { __FICUS_BUILTIN_CSS_FINGERPRINT__: JSON.stringify(await computeBuiltinCssFingerprint()) },
  })
  if (!build.success) throw new Error(build.logs.join('\n'))
  return `\n      // Generated by scripts/generate-theme-flash.ts — do not edit by hand.\n      ${(await build.outputs[0]!.text()).trim()}\n    `
}

if (import.meta.main) {
  const html = Bun.file(resolve(import.meta.dir, '../index.html'))
  const script = await generateThemeFlash()
  await Bun.write(
    html,
    (await html.text()).replace(
      /(<script data-ficus-theme-flash>)[\s\S]*?(<\/script>)/,
      (_, start, end) => `${start}${script}${end}`
    )
  )
}
