import {
  DEFAULT_THEME_ID,
  resolveThemeSelection,
  type EffectiveAppearance,
  type StoredThemeSelection,
  type ThemeDescriptor,
  type ThemeKind,
} from '@ficus/shared/theme-schema'

/** Built-in values live in CSS, never in a second runtime JS palette.
 * Iris's pair is the unscoped base in index.css; every other complete scope,
 * the default Ficus pair included, lives in builtins.css.
 */
export interface WebThemeDefinition extends ThemeDescriptor {
  readonly id: string
  readonly label: string
  readonly kind: ThemeKind
  /**
   * The class added to <html> per resolved variant (null = no class). The
   * light variant of `iris` uses the unscoped `:root` defaults, the dark
   * variant keeps the literal `dark` class so existing Tailwind `dark:`
   * variants keep working through the migration (report §4.1).
   */
  readonly variantClass: Partial<Record<EffectiveAppearance, string | null>>
}

/** The default pair: the Ficus brand palette (leaf primary, terracotta secondary, moss tertiary over linen and
 * soil surfaces), generated by apps/web/scripts/generate-palette-builtins.ts (see docs/wiki/theme/builtins.md). */
export const FICUS_THEME: WebThemeDefinition = {
  id: 'ficus',
  label: 'Ficus',
  kind: 'dual',
  variantClass: { light: null, dark: 'dark' },
}

/** The original purple pair, with the narrow phase-5 contrast corrections; the unscoped base in index.css. */
export const IRIS_THEME: WebThemeDefinition = {
  id: 'iris',
  label: 'Iris',
  kind: 'dual',
  variantClass: { light: null, dark: 'dark' },
}

export const HIGH_CONTRAST_THEME_ID = 'high-contrast'

/** Built-in themes available without any custom-theme machinery. */
export const BUILT_IN_THEMES: readonly WebThemeDefinition[] = [
  FICUS_THEME,
  IRIS_THEME,
  // Cool slate surfaces and a restrained teal accent; familiar Iris geometry.
  { id: 'harbor', label: 'Harbor', kind: 'dual', variantClass: { light: null, dark: 'dark' } },
  // Warm paper/charcoal surfaces with a terracotta accent, not a semantic recolor.
  { id: 'ember', label: 'Ember', kind: 'dual', variantClass: { light: null, dark: 'dark' } },
  // Six BigBrain-ported palettes (docs/wiki/theme/builtins.md); each is a
  // constant-appearance built-in generated by
  // apps/web/scripts/generate-bigbrain-builtins.ts from BigBrain's own
  // bg/fg/activity triples. The dark ones keep the literal `dark` class (the
  // same migration bridge Iris's own dark variant uses) so any remaining
  // Tailwind `dark:` variant still applies.
  { id: 'nurebairo', label: 'nurebairo', kind: 'unified', variantClass: { constant: 'dark' } },
  { id: 'phosphorus', label: 'Phosphorus', kind: 'unified', variantClass: { constant: null } },
  { id: 'yamabukiiro', label: 'yamabukiiro', kind: 'unified', variantClass: { constant: null } },
  { id: 'moegiiro', label: 'moegiiro', kind: 'unified', variantClass: { constant: 'dark' } },
  { id: 'adzukiiro', label: 'adzukiiro', kind: 'unified', variantClass: { constant: 'dark' } },
  { id: 'asagiiro', label: 'asagiiro', kind: 'unified', variantClass: { constant: 'dark' } },
  // Constant light scheme: stark ink/paper, strong outlines and dark code panels. Always listed last (see
  // highContrastLast).
  { id: HIGH_CONTRAST_THEME_ID, label: 'High contrast', kind: 'unified', variantClass: { constant: null } },
]

/**
 * High contrast is an accessibility choice rather than a palette, so every theme picker lists it after all other
 * themes, the user's saved presets included.
 */
export function highContrastLast<T extends { kind: string; id: string }>(options: readonly T[]): T[] {
  const isHighContrast = (option: T) => option.kind === 'builtin' && option.id === HIGH_CONTRAST_THEME_ID
  return [...options.filter((option) => !isHighContrast(option)), ...options.filter(isHighContrast)]
}

/** Release gate passed: all built-in contrast and pre-paint matrices (phase 5).
 * Keep the switch for a quick picker rollback without losing stored choices. */
export const THEME_PICKER_ENABLED = true

export function findWebTheme(themeId: string | null | undefined): WebThemeDefinition {
  return (
    BUILT_IN_THEMES.find((theme) => theme.id === themeId) ??
    BUILT_IN_THEMES.find((theme) => theme.id === DEFAULT_THEME_ID)!
  )
}

export const KNOWN_THEME_IDS: readonly string[] = BUILT_IN_THEMES.map((theme) => theme.id)

export interface ResolvedWebTheme {
  readonly theme: WebThemeDefinition
  readonly appearance: EffectiveAppearance
}

/**
 * Resolve (themeId, appearance) with the shared fallback rules: unknown id →
 * default theme; unified ignores appearance; 'system' resolves against the OS
 * preference. Never derives colors.
 */
export function resolveWebTheme(
  themeId: string | null | undefined,
  appearance: StoredThemeSelection['appearance'] | null | undefined,
  systemPrefersDark: boolean
): ResolvedWebTheme {
  return resolveThemeSelection(BUILT_IN_THEMES, themeId, appearance, systemPrefersDark)
}
