# Headless service enables DNS for individual pods:
#   <pod-name>.ficus-sandboxes.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: ficus-sandboxes
  namespace: ficus-sandboxes
spec:
  clusterIP: None
  selector:
    app: ficus-sandbox
  ports:
    - port: 50051
      targetPort: http
      protocol: TCP
      name: http
