import {
  ActivityIcon,
  AgentIcon,
  BellIcon,
  CalendarIcon,
  ClipboardIcon,
  CloudIcon,
  CpuIcon,
  DecisionIcon,
  DeviceIcon,
  DeviceProIcon,
  DownloadIcon,
  FolderIcon,
  GitBranchIcon,
  GlobeIcon,
  KeyIcon,
  LightningIcon,
  LinkIcon,
  LogsIcon,
  MailIcon,
  MarkdownIcon,
  MemoryIcon,
  MonitorIcon,
  PaletteIcon,
  ParticipantsIcon,
  PuzzleIcon,
  SettingsIcon,
  ShieldIcon,
  SquadIcon,
  TerminalIcon,
  UserIcon,
  WorkflowIcon,
  WindowLayoutIcon,
} from '../icons'

export const SETTINGS_SECTION_ICONS = {
  general: SettingsIcon,
  context: MarkdownIcon,
  workspace: FolderIcon,
  access: TerminalIcon,
  account: UserIcon,
  appearance: PaletteIcon,
  app: WindowLayoutIcon,
  mobile: DeviceIcon,
  'mobile-pro': DeviceProIcon,
  notifications: BellIcon,
  devices: MonitorIcon,
  sessions: CalendarIcon,
  workflows: WorkflowIcon,
  'agent-types': AgentIcon,
  skills: PuzzleIcon,
  integrations: LinkIcon,
  users: ParticipantsIcon,
  roles: ShieldIcon,
  'system-tokens': KeyIcon,
  signup: MailIcon,
  'squad-presets': SquadIcon,
  git: GitBranchIcon,
  'notification-rules': ClipboardIcon,
  providers: CpuIcon,
  'decision-providers': DecisionIcon,
  memory: MemoryIcon,
  amtp: GlobeIcon,
  machines: CloudIcon,
  'remote-hosts': TerminalIcon,
  system: ActivityIcon,
  storage: FolderIcon,
  'system-logs': LogsIcon,
  'ops-insights': LightningIcon,
  updates: DownloadIcon,
} as const
