import './sprites.css'
import './theme.css'
import type { FarmSkin } from '../types'
import {
  FuturistAvatar,
  FuturistBadge,
  FuturistCompost,
  FuturistCrates,
  FuturistDecor,
  FuturistDefs,
  FuturistFarmhouse,
  FuturistGround,
  FuturistHut,
  FuturistMailbox,
  FuturistPlant,
  FuturistPlot,
  FuturistRobot,
  FuturistSeedShed,
  FuturistSign,
  FuturistStand,
  FuturistYard,
} from './sprites'

/** Minimal and futuristic: an endless line grid, line-art plants and floating orbs, in three colours. */
export const futuristSkin: FarmSkin = {
  id: 'futurist',
  label: 'Futurist',
  className: 'g-skin-futurist',
  Defs: FuturistDefs,
  Ground: FuturistGround,
  YardBack: FuturistYard,
  yardFront: () => [],
  Sign: FuturistSign,
  PlotGround: FuturistPlot,
  Plant: FuturistPlant,
  Badge: FuturistBadge,
  badgeLift: (plot) => (plot.state === 'review' ? -40 : -34),
  Robot: FuturistRobot,
  Avatar: FuturistAvatar,
  avatarViewBox: '-20 -20 40 40',
  Hut: FuturistHut,
  Stand: FuturistStand,
  Farmhouse: FuturistFarmhouse,
  SeedShed: FuturistSeedShed,
  Mailbox: FuturistMailbox,
  Crates: FuturistCrates,
  Compost: FuturistCompost,
  Decor: FuturistDecor,
  boxes: {
    robot: [-18, -46, 36, 52],
    plant: [-26, -44, 52, 56],
    sign: [-10, -36, 140, 42],
    hut: [-44, -48, 88, 64],
    stand: [-40, -50, 80, 66],
    farmhouse: [-90, -110, 180, 140],
    seedShed: [-54, -70, 108, 90],
    mailbox: [-24, -60, 48, 70],
    crates: [-40, -30, 80, 44],
    compost: [-30, -26, 60, 38],
  },
  worldPad: { top: 80, side: 40, bottom: 30 },
}
