import { Permissions, type Permission } from './permissions'

/** User-facing help for the permission checks in Core. Keep entries in sync with their route guards. */
export const PERMISSION_DESCRIPTIONS = {
  '*': 'Grant every permission, including permissions added in future versions.',
  'squads:read': 'View squads, their activity and source configuration, and worker status.',
  'squads:create': 'Create squads and view the available setup options.',
  'squads:delete': 'Archive squads.',
  'squads:update': 'Edit squad settings, ordering, source configuration, and toolchains.',
  'agents:read': 'View agents, messages, execution history, and streamed output.',
  'agents:write': 'Upload images for agents and squads. Agent settings use agents:update.',
  'agents:create': 'Spawn agents in a squad.',
  'agents:run': 'Start, interrupt, and steer agents, send follow-ups, and answer their questions.',
  'agents:terminate': 'Unspawn flexible squad agents while keeping their stored records.',
  'agents:scopes:read': 'View extra permission grants attached to an agent.',
  'agents:scopes:manage': 'Grant or revoke extra agent permissions, within the caller’s own authority.',
  'agents:update': 'Edit agent settings, including model and execution configuration.',
  'agents:delete': 'Delete agent records.',
  'workstreams:read': 'View work streams, their flow, progress, history, and metadata.',
  'workstreams:create': 'Create work streams, including ones with an inline custom flow.',
  'workstreams:update': 'Edit work streams and control their lifecycle, including pause, resume, and waits.',
  'workstreams:review': 'Approve or reject human approval steps in a squad’s workflows. Human users only.',
  'workstreams:revise-flow': 'Revise a work stream’s flow definition, subject to its handoff policy.',
  'workstreams:delete': 'Delete work streams.',
  'workstreams:respond': 'Resolve work-stream waits, approve work, send it back, and unblock it.',
  'workstreams:manage-agents': 'Assign agents to work streams or remove their assignments.',
  'chat:read': 'Search squad chat messages. Reading an agent’s history also uses agents:read.',
  'chat:send': 'Send chat messages, use the text assistant, and upload chat attachments.',
  'terminal:access': 'Open and interact with sandbox terminals, including running shell commands.',
  'terminal:read': 'List squad terminal and workspace sessions.',
  'terminal:write': 'Close squad terminal sessions. Opening a terminal requires terminal:access.',
  'sandbox:logs': 'Stream sandbox or container logs without opening an interactive terminal.',
  'ssh:read': 'View squad SSH key names, public keys, SSH configuration, and known hosts.',
  'ssh:write': 'Manage squad SSH keys, SSH configuration, and trusted host entries.',
  'env:read': 'Read squad environment variables and environment-secret configuration.',
  'env:write': 'Set squad environment variables and manage which secrets are exposed to agents.',
  'integrations:read': 'View integration configuration and connections across providers. Does not reveal credentials.',
  'integrations:use':
    'Use connected integration accounts through Ficus, subject to squad access and provider permissions.',
  'integrations:write':
    'Enable integrations, configure credentials and webhooks, and manage accounts and squad connections.',
  'integrations:export': 'Send conversation content to connected external services. Does not export credentials.',
  'memory:read': 'Browse, download, and search squad memory and view its synchronization status.',
  'memory:write': 'Create and edit squad memory and manage its indexing and synchronization.',
  'inbox:read': 'Read inbox messages and attachments within the caller’s allowed inboxes.',
  'inbox:write': 'Send and manage inbox messages and attachments, subject to recipient and ownership checks.',
  'inbox:system': 'Read and post shared system announcements and operational notifications.',
  'inbox:read-squad': 'Read other agents’ inboxes within an accessible squad.',
  'amtp:read': 'View federation identity, peers, remote agents, and delivery information.',
  'amtp:write': 'Manage federation peers, agent registrations, and federation configuration.',
  'amtp:send': 'Discover and message agents on connected Ficus instances.',
  'amtp:register': 'Register or update the calling agent’s federation identity.',
  'workspace:read': 'Browse, search, read, and download squad workspace files.',
  'workspace:write': 'Upload files into squad workspaces.',
  'schedules:read': 'View schedules and their execution history.',
  'schedules:create': 'Create schedules for recurring work.',
  'schedules:update': 'Edit, enable, disable, and manage existing schedules.',
  'schedules:delete': 'Delete schedules.',
  'schedules:trigger': 'Run a schedule immediately.',
  'squad-relationships:read': 'View reporting, collaboration, and dependency relationships between squads.',
  'squad-relationships:write': 'Create and remove relationships between squads.',
  'ai:voice': 'Start voice assistant sessions and obtain streaming transcription credentials.',
  'ai:extract': 'Use AI to extract structured form fields from text.',
  'ai:transcribe': 'Convert uploaded or streamed audio into text.',
  'ai:tts': 'Generate spoken audio from text and accessible messages.',
  'actions:read': 'View pending agent questions and work-stream actions within the caller’s access.',
  'recommendations:read': 'View operational recommendations for accessible squads.',
  'recommendations:update': 'Update the status of operational recommendations.',
  'secrets:read': 'Read stored secret values in all groups, except protected or retired credentials.',
  'secrets:write': 'Set or delete stored secrets in all groups, except protected or retired credentials.',
  'secrets:read:integration':
    'Read integration-group secrets, including Git author overrides. Integration accounts have separate permissions.',
  'secrets:write:integration': 'Set or delete remaining secrets in the integration group.',
  'secrets:read:provider':
    'Read remaining secrets in the provider group. AI provider accounts have separate permissions.',
  'secrets:write:provider': 'Set or delete remaining secrets in the provider group.',
  'secrets:read:notification': 'Read remaining secrets in the notification group.',
  'secrets:write:notification': 'Set or delete remaining secrets in the notification group.',
  'secrets:read:system':
    'Read system-group secrets, such as Ficus credentials and encryption keys, except protected keys.',
  'secrets:write:system':
    'Set or delete system-group secrets, such as Ficus credentials and encryption keys, except protected keys.',
  'roles:read': 'View roles and the permissions they grant.',
  'roles:create': 'Create custom roles and choose their permissions.',
  'roles:update': 'Edit custom roles and change their permissions.',
  'roles:delete': 'Delete custom roles.',
  'users:read': 'View users, role assignments, and seat availability.',
  'users:create': 'Create or invite users and resend invitations.',
  'users:update': 'Edit user accounts, enable or disable them, and manage role assignments.',
  'users:delete': 'Delete user accounts.',
  'settings:read': 'View global settings, notification rules, and global secret-exposure configuration.',
  'settings:write': 'Change global settings, notification rules, and global secret-exposure configuration.',
  'channels:read': 'View and export channel configurations.',
  'channels:create': 'Create channel configurations.',
  'channels:update': 'Edit, enable, disable, or restore channel configurations.',
  'channels:delete': 'Delete channel configurations.',
  'skills:read': 'View and export skills and compare them with their templates.',
  'skills:write': 'Create, import, edit, delete, and manage skills and their supporting files.',
  'slots:use': 'View coordination pools and claim, renew, release, or wait for slots as an agent.',
  'slots:write': 'Manage coordination pools and inspect diagnostics, in addition to using slots.',
  'monitors:read': 'View background monitors and their logs.',
  'monitors:write': 'Cancel background monitors.',
  'machines:read': 'View sandbox host machines and their status.',
  'machines:write': 'Provision, configure, and manage host machines and move sandboxes between them.',
  'machines:force-migrate': 'Authorize forced migration of sandboxes; the operation also requires machines:write.',
  'remote-hosts:read': 'View remote SSH targets and refresh the caller’s permitted squad host configuration.',
  'remote-hosts:write': 'Manage remote SSH targets, their credentials, and squad access grants.',
  'deployments:read': 'View external deployment records, local apps, and local app logs.',
  'deployments:write': 'Manage deployment records and start, stop, or restart local apps.',
  'deployments:delete': 'Remove deployment records and local apps.',
  'artifacts:read': 'Browse and download agent artifacts and their files.',
  'artifacts:write': 'Manage artifact files and prepare artifact preview environments.',
  'grants:read': 'View resource access grants between squads.',
  'grants:write': 'Create or revoke resource access grants between squads.',
  'updates:read': 'Check for Ficus updates and view update settings and status.',
  'updates:write': 'Change update settings and apply Ficus updates.',
  'routing:read': 'Request squad-routing suggestions for a question.',
  'agent-types:read': 'View and export agent types, model tiers, and the model catalog.',
  'agent-types:create': 'Create agent types.',
  'agent-types:update': 'Edit agent types, their skills, model tiers, and template overrides.',
  'agent-types:delete': 'Delete agent types.',
  'squad-presets:read': 'View and export squad preset definitions and compare them with templates.',
  'squad-presets:create': 'Create squad presets.',
  'squad-presets:update': 'Edit, enable, disable, or restore squad preset definitions.',
  'squad-presets:delete': 'Delete squad presets.',
  'workflows:read': 'View saved workflow presets and their definitions.',
  'workflows:create': 'Create saved workflow presets.',
  'workflows:update': 'Edit and manage saved workflow presets.',
  'workflows:delete': 'Delete saved workflow presets.',
  'provider-auth:read': 'View AI provider accounts, connection status, and model-routing configuration.',
  'provider-auth:write': 'Connect and manage AI provider accounts, credentials, priority, and model routing.',
  'webhooks:read': 'View webhook setup and delivery status.',
  'system:pause': 'View and manage instance-wide execution pauses and maintenance leases.',
  'system:restart': 'Restart Ficus services.',
  'system:cleanup': 'Clean up inactive agents and run workspace or package-store garbage collection.',
  'system:logs': 'Read system diagnostics and stream Ficus service logs.',
  'system:demo': 'Seed and manage the app-store reviewer demo account on a designated demo instance.',
  'system-tokens:manage': 'Create, list, and revoke system API tokens, including choosing their permission scopes.',
  'theme-presets:moderate':
    'Remove another user’s theme preset from the instance-wide shared list. The owner keeps a private copy.',
  'farm:read': 'See the farm’s chat rooms and messages, and who else is on the farm.',
  'farm:chat': 'Talk to other people on the farm: post, react, send direct messages, and appear to others.',
  'farm:manage-rooms': 'Create, rename, and delete the farm’s chat rooms (the general room always stays).',
} satisfies Record<Permission, string>

export const PERMISSION_CATALOG = Object.values(Permissions)
  .filter((permission) => permission !== '*')
  .map((permission) => ({
    permission,
    resource: permission.split(':')[0]!,
    description: PERMISSION_DESCRIPTIONS[permission],
  }))
