#!/usr/bin/env bash
# Deploy Ficus services: core (API/worker via ECR+K8s) and/or web (S3+CloudFront).
#
# Usage: ./scripts/deploy.sh [--target core|api|worker|sandbox|web|all] [--namespace NAMESPACE] [--tag TAG] [--version VERSION]
#
# Environment:
#   KUBECONFIG       - Path to Ficus kubeconfig (default: $HOME/.kube/tau-config)
#   AWS_REGION       - AWS region (default: us-east-2)
#   K8S_NAMESPACE    - Core namespace (required for Kubernetes targets)
#   IMAGE_TAG        - Image tag (default: latest)
#   WEB_VERSION      - Web version prefix in S3 (default: latest)
#   WEB_BUCKET       - S3 bucket for web assets (default: tau-web-static)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Use Ficus kubeconfig (generated by 'bun run tau:kubeconfig' in the ops repo)
export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/tau-config}"

NAMESPACE="${K8S_NAMESPACE:-}"
TAG="${IMAGE_TAG:-latest}"
TARGET="all"
VERSION="${WEB_VERSION:-latest}"
BUCKET="${WEB_BUCKET:-tau-web-static}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)    TARGET="$2"; shift 2 ;;
    --namespace) NAMESPACE="$2"; shift 2 ;;
    --tag)       TAG="$2"; shift 2 ;;
    --version)   VERSION="$2"; shift 2 ;;
    *)           echo "Unknown arg: $1"; exit 1 ;;
  esac
done

ensure_kubeconfig() {
  if [[ -z "$NAMESPACE" ]]; then
    echo "Error: set K8S_NAMESPACE or pass --namespace before deploying."
    exit 1
  fi
  if [[ ! -f "$KUBECONFIG" ]]; then
    echo "Error: kubeconfig not found at $KUBECONFIG"
    echo "Run 'bun run tau:kubeconfig' in the ops repo to generate it."
    exit 1
  fi
}

ecr_login() {
  echo "=== ECR Login ==="
  "$SCRIPT_DIR/ecr-login.sh"
  echo ""
}

build_and_push() {
  local filter="${1:-}"
  ecr_login

  echo "=== Build & Push Images ==="
  IMAGE_TAG="$TAG" "$SCRIPT_DIR/ecr-push-images.sh" $filter
  echo ""
}

restart_deployments() {
  local deployments=("$@")
  echo "=== Restart Deployments (namespace: $NAMESPACE) ==="
  kubectl -n "$NAMESPACE" rollout restart deployment "${deployments[@]}"

  echo ""
  echo "=== Waiting for rollout ==="
  for deploy in "${deployments[@]}"; do
    echo "Waiting for $deploy..."
    kubectl -n "$NAMESPACE" rollout status deployment "$deploy" --timeout=300s
  done
  echo ""
}

deploy_core() {
  ensure_kubeconfig
  build_and_push --core-only
  restart_deployments tau-api tau-worker
  echo "Core deploy complete."
}

deploy_api() {
  ensure_kubeconfig
  build_and_push --core-only
  restart_deployments tau-api
  echo "API deploy complete."
}

deploy_worker() {
  ensure_kubeconfig
  build_and_push --core-only
  restart_deployments tau-worker
  echo "Worker deploy complete."
}

deploy_sandbox() {
  ensure_kubeconfig
  build_and_push --sandbox-only

  local SANDBOX_NS="${NAMESPACE/tau-core-/tau-sandboxes-}"
  echo "=== Kill sandbox pods (namespace: $SANDBOX_NS) ==="
  kubectl -n "$SANDBOX_NS" delete pods --all --force
  echo ""
  echo "Sandbox deploy complete."
}

deploy_web() {
  local DIST="$ROOT_DIR/apps/web/dist"

  echo "=== Build Web ==="
  cd "$ROOT_DIR"
  bun run build:web
  echo ""

  if [[ ! -d "$DIST" ]]; then
    echo "Error: dist directory not found at $DIST"
    echo "Web build may have failed."
    exit 1
  fi

  echo "=== Sync to S3 (s3://$BUCKET/$VERSION/) ==="
  aws s3 sync "$DIST" "s3://$BUCKET/$VERSION/" --delete
  echo ""

  echo "=== Invalidate CloudFront ==="
  DIST_IDS=$(aws cloudfront list-distributions \
    --query "DistributionList.Items[?contains(Comment, \`Tau web SPA — version $VERSION\`) || Comment==\`Tau splash page — ficus.sh\`].Id" \
    --output text)

  if [[ -z "$DIST_IDS" ]]; then
    echo "Warning: No CloudFront distributions found for version $VERSION"
  else
    for DIST_ID in $DIST_IDS; do
      echo "Invalidating CloudFront $DIST_ID..."
      aws cloudfront create-invalidation \
        --distribution-id "$DIST_ID" \
        --paths "/*" \
        --no-cli-pager \
        --output text \
        --query "Invalidation.Id"
    done
  fi

  echo ""
  echo "Web deploy complete."
}

case "$TARGET" in
  core)    deploy_core ;;
  api)     deploy_api ;;
  worker)  deploy_worker ;;
  sandbox) deploy_sandbox ;;
  web)     deploy_web ;;
  all)
    ensure_kubeconfig
    build_and_push
    restart_deployments tau-api tau-worker

    SANDBOX_NS="${NAMESPACE/tau-core-/tau-sandboxes-}"
    echo "=== Kill sandbox pods (namespace: $SANDBOX_NS) ==="
    kubectl -n "$SANDBOX_NS" delete pods --all --force
    echo ""

    deploy_web
    ;;
  *)
    echo "Error: Unknown target '$TARGET'. Use core, api, worker, sandbox, web, or all."
    exit 1
    ;;
esac

echo ""
echo "Deploy complete."
