/**
 * Per-box devbox comfort-set seeding.
 *
 * The k8s sandbox IMAGE baked a "comfort set" of ergonomic CLI tools directly
 * into the box:
 *  - the `agent` stage installed a LIGHT set (node/python + ripgrep/fd/tree/less/
 *    gh/tmux/procps) into the GLOBAL nix profile, on PATH the instant the pod
 *    started (see packages/k8s-sandbox/Dockerfile `agent` stage);
 *  - the `squad` stage baked a HEAVIER devbox toolchain (adds bun/jq/gnumake/gcc/
 *    diffutils/patch/perl) from packages/k8s-sandbox/sandbox/devbox.json.
 *
 * A VM box runs on bare Ubuntu with no such image, so its shells lack the comfort
 * set until we seed one. This module materializes a per-user `devbox` at the
 * box's `FICUS_DEVBOX_DIR` (`~/.tau/devbox`, see packages/k8s-sandbox/src/paths.ts)
 * and runs `devbox install` — AS THE BOX USER, because the sandbox-server executes
 * every `/write` and `/bash` as that user (never root), and the box user owns
 * `~/.tau`.
 *
 * ## Idempotency (the slice-2 sync-on-every-ensure lesson)
 * `devbox install` is slow (minutes). We must NOT pay that on every ensure, so we
 * hash the intended `devbox.json` content and, after a SUCCESSFUL install, record
 * that hash in `~/.tau/devbox/.seeded`. A later ensure whose intended content
 * hashes to the same marker SKIPS the install entirely; a CHANGED comfort set
 * (different hash) forces a fresh install. The marker is written ONLY after a
 * successful install, so a failed install re-attempts on the next ensure.
 *
 * ## Failure semantics (NON-fatal — the caller's contract)
 * Unlike file-sync (fatal: a box missing its CLI/skills/identity is broken), a box
 * without the comfort set still works with a DEGRADED shell (no `rg`/`fd`/etc.).
 * `seedBoxDevbox` therefore THROWS on failure so the caller can decide; the
 * VmSandboxManager wraps the call in a try/catch, logs WARN, and lets the ensure
 * proceed.
 *
 * ## devbox.lock cache (the 48s Nixhub-resolve lesson)
 * Most comfort-set packages use `@latest`, and a brand-new box starts with
 * no `devbox.lock`, so `devbox install` resolves every package against Jetify's
 * Nixhub API over the network — 48s+ measured live, even with a fully warm local
 * `/nix/store` (see jetify-com/devbox `internal/lock/lockfile.go`'s `File.Resolve`:
 * it returns the existing lock entry's `Resolved` value without ever calling
 * `FetchResolvedPackage` — the Nixhub-backed resolver — when one is already
 * present). We cache the devbox.lock generated by the FIRST successful install of
 * a given comfort set (keyed by {@link computeDevboxSeedHash}, the sha256 prefix
 * of the pristine `devbox.json`) and seed it into every later box's devbox dir
 * BEFORE running `devbox install`, so `devbox` resolves from the local lock
 * instead of the network. The cache is machine-independent (per-system lock
 * entries cover `x86_64-linux`, which is every tau machine), so it benefits new
 * machines too.
 *
 * This ONLY applies when the devbox.json being installed is the exact pristine
 * role render — a user-customized devbox.json never reads or writes the cache,
 * since its resolution isn't guaranteed to match the pristine set's.
 *
 * There is no time-based or content-based invalidation beyond the hash itself:
 * once a lock is cached, `@latest` is FROZEN at whatever Nixhub resolved at
 * first-cache time until the comfort set's content changes (a deliberate
 * determinism trade — every box gets the identical resolution, not whatever
 * Nixhub happens to answer today). To force a refresh (e.g. to pick up newer
 * package versions) without changing the comfort set, manually delete the
 * `devbox_lock_cache` row for the affected hash.
 */

import { createHash } from 'crypto'
import { SandboxHttpError, type BashResponse, type SandboxClient } from '../sandbox/k8s/http-client'
import { DevboxLockCache } from '../../entities/DevboxLockCache'
import { createLogger } from '../../lib/infra/logger'
import { boxUnixUser } from './box-manager'
import type { BoxStepTimings } from './box-timing'

const log = createLogger('devbox-seed')

/** Role of a box, mirroring `EnsureBoxOpts['role']` / pod-spec's `sandboxType`. */
export type SeedBoxRole = 'squad' | 'agent' | 'system-manager'

/** devbox.json schema pin, matching the k8s-sandbox baked templates. */
const DEVBOX_SCHEMA = 'https://raw.githubusercontent.com/jetify-com/devbox/0.14.0/.schema/devbox.schema.json'

/**
 * gh is pinned directly to Nixpkgs (2.100.0) because the Jetify version index
 * lags the 2.99.0 minimum for native attachments. Keep the ref in sync with
 * packages/k8s-sandbox/Dockerfile and sandbox/devbox.json.
 *
 * LIGHT comfort set — mirrors the k8s `agent` stage's global nix profile install
 * (packages/k8s-sandbox/Dockerfile). Kept in lockstep with that stage; if the
 * Dockerfile's agent comfort set changes, update this list (and the test).
 */
export const AGENT_COMFORT_PACKAGES: readonly string[] = [
  'nodejs_24@latest',
  'python3@latest',
  'ripgrep@latest',
  'fd@latest',
  'tree@latest',
  'less@latest',
  'github:NixOS/nixpkgs/d5dfd8e6716dde34398bc14bc87c10dece9c8c68#gh',
  'tmux@latest',
  'procps@latest',
]

/**
 * bun is pinned to a Nixpkgs commit carrying the repository's `.bun-version`
 * (1.4.2): the Jetify version index lags Nixpkgs, so `bun@latest` resolved to an
 * older release than a squad toolchain's plain `bun`, leaving two versions on
 * one box. Bump the ref together with `.bun-version`.
 */
const BUN_PACKAGE = 'github:NixOS/nixpkgs/8825bebf6324e0579d012936eff73379af284b6d#bun'

/**
 * HEAVIER comfort set — mirrors packages/k8s-sandbox/sandbox/devbox.json (the
 * `squad` stage's baked toolchain). squad AND system-manager boxes run the heavy
 * runtime, so both get this set (agent boxes get the light one above).
 */
export const SQUAD_COMFORT_PACKAGES: readonly string[] = [
  'nodejs_24@latest',
  BUN_PACKAGE,
  'python3@latest',
  'ripgrep@latest',
  'fd@latest',
  'jq@latest',
  'tree@latest',
  'less@latest',
  'github:NixOS/nixpkgs/d5dfd8e6716dde34398bc14bc87c10dece9c8c68#gh',
  'gnumake@latest',
  'gcc@latest',
  'diffutils@latest',
  'patch@latest',
  'perl@latest',
  'procps@latest',
  'tmux@latest',
]

/** `devbox install` budget — the comfort set is a slow, one-time realization. */
const DEFAULT_INSTALL_TIMEOUT_SECONDS = 600 // 10 minutes

/** Injectable seams for {@link seedBoxDevbox}; each defaults to production. */
export interface SeedBoxDevboxDeps {
  /** The box user's HOME (`/home/box_<hash>`). */
  boxHome?: (sandboxId: string) => string
  /** `devbox install` timeout budget (seconds). */
  installTimeoutSeconds?: number
  /** Clock authority for the devbox-resolve/devbox-realize split (see {@link runDevboxInstall}). Defaults to `Date.now`. */
  now?: () => number
  /**
   * Look up a cached `devbox.lock` by seed hash. Defaults to the DB-backed
   * {@link DevboxLockCache}. Best-effort: a rejection is caught, logged at
   * WARN, and treated as a cache miss — it never fails or delays the seed.
   */
  cacheGet?: (seedHash: string) => Promise<string | null>
  /**
   * Store a generated `devbox.lock` under `seedHash`, first-write-wins.
   * Defaults to the DB-backed {@link DevboxLockCache}. Best-effort: a
   * rejection is caught and logged at WARN — the seed still succeeds.
   */
  cachePut?: (seedHash: string, lockContent: string) => Promise<void>
}

function defaultBoxHome(sandboxId: string): string {
  return `/home/${boxUnixUser(sandboxId)}`
}

function packagesForRole(role: SeedBoxRole): readonly string[] {
  return role === 'agent' ? AGENT_COMFORT_PACKAGES : SQUAD_COMFORT_PACKAGES
}

/**
 * The intended `devbox.json` content for a role. Deterministic: the same role
 * always renders byte-identical output, so its hash is a stable seed marker.
 */
export function renderDevboxJson(role: SeedBoxRole): string {
  const doc = {
    $schema: DEVBOX_SCHEMA,
    packages: packagesForRole(role),
    shell: { init_hook: [] as string[], scripts: {} },
  }
  return `${JSON.stringify(doc, null, 2)}\n`
}

/** Short content hash of a role's intended devbox.json — the `.seeded` marker. */
export function computeDevboxSeedHash(role: SeedBoxRole): string {
  return createHash('sha256').update(renderDevboxJson(role)).digest('hex').slice(0, 16)
}

/** Keep installation and bounded cache maintenance in the same fenced command.
 * Nix 2.24 writes loose duplicates even when shared Git alternates are present.
 * The EXIT trap also cleans partial failed installs without masking their status.
 * Older machine scripts are tolerated during rolling upgrades.
 */
export function devboxInstallCommand(devboxDir: string): string {
  const cleanup =
    'if [ -f /opt/tau/bin/box-provision.sh ]; then timeout 15s bash /opt/tau/bin/box-provision.sh --unix-user "$(id -un)" --prepare-nix-cache >&2 || true; fi'
  return `cd ${shellQuote(devboxDir)} && (trap ${shellQuote(cleanup)} EXIT; devbox install)`
}

export function computeDevboxInstallInvocationId(sandboxId: string, role: SeedBoxRole): string {
  const hash = computeDevboxSeedHash(role)
  const devboxDir = `${defaultBoxHome(sandboxId)}/.tau/devbox`
  const command = devboxInstallCommand(devboxDir)
  const commandDigest = createHash('sha256').update(command).digest('hex')
  return createHash('sha256').update(`${sandboxId}\0${hash}\0devbox-install\0${commandDigest}`).digest('hex')
}

type DevboxPackageList = string[]
/** devbox's map form: `name → version | { version?, outputs?, … }`. */
type DevboxPackageMap = Record<string, string | Record<string, unknown>>
type DevboxDocument = Record<string, unknown> & { packages: DevboxPackageList | DevboxPackageMap }

type DevboxMergeResult = {
  content: string
  shouldWrite: boolean
}

/** A Nixpkgs pin (`github:NixOS/nixpkgs/<rev>#bun`) is named by its attribute. */
function packageBaseName(pkg: string): string {
  const pinned = /^github:NixOS\/nixpkgs\/[^#]+#(.+)$/.exec(pkg)
  return pinned ? pinned[1]! : pkg.split('@')[0]
}

/**
 * Comfort specs an earlier Core wrote itself, mapped to what replaces them.
 * Replacing only these exact specs upgrades existing boxes without overriding
 * a version the user chose (`bun@1.2.0` stays).
 */
const SUPERSEDED_COMFORT_SPECS: Readonly<Record<string, string>> = { 'bun@latest': BUN_PACKAGE }

function supersededBy(role: SeedBoxRole, spec: string): string | undefined {
  const replacement = SUPERSEDED_COMFORT_SPECS[spec]
  return replacement && packagesForRole(role).includes(replacement) ? replacement : undefined
}

/** Swap Core's own superseded specs in place, keeping the file's shape and order. */
function replaceSupersededSpecs(
  role: SeedBoxRole,
  packages: DevboxPackageList | DevboxPackageMap
): { packages: DevboxPackageList | DevboxPackageMap; replaced: boolean } {
  let replaced = false
  if (Array.isArray(packages)) {
    const next = packages.map((spec) => {
      const replacement = supersededBy(role, spec)
      if (!replacement) return spec
      replaced = true
      return replacement
    })
    return { packages: next, replaced }
  }
  const next = Object.fromEntries(
    Object.entries(packages).map(([name, value]) => {
      const replacement = typeof value === 'string' ? supersededBy(role, value ? `${name}@${value}` : name) : undefined
      if (!replacement) return [name, value]
      replaced = true
      return splitPackageSpec(replacement)
    })
  )
  return { packages: next, replaced }
}

/** `nodejs_24@latest` → `["nodejs_24", "latest"]`; a bare flake ref (`github:…#gh`) has no version (`""`). */
function splitPackageSpec(spec: string): [name: string, version: string] {
  const at = spec.lastIndexOf('@')
  return at > 0 ? [spec.slice(0, at), spec.slice(at + 1)] : [spec, '']
}

function isPackageList(value: unknown): value is DevboxPackageList {
  return Array.isArray(value) && value.every((pkg): pkg is string => typeof pkg === 'string')
}

/**
 * devbox rewrites `packages` into a map as soon as any entry carries options
 * (`devbox add zlib --outputs dev`). Every value is a version string or an
 * options object; anything else means the file is not a devbox.json we can
 * reason about.
 */
function isPackageMap(value: unknown): value is DevboxPackageMap {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return false
  return Object.values(value as Record<string, unknown>).every(
    (entry) => typeof entry === 'string' || (entry !== null && typeof entry === 'object' && !Array.isArray(entry))
  )
}

/**
 * Merge missing role comfort packages without taking ownership of user
 * configuration. Both devbox shapes are preserved as-is: a list stays a list
 * (specs appended), a map stays a map (`name: version` pairs appended) — never
 * flatten a map back to a list, that would drop the options the user added.
 */
export function mergeDevboxJson(role: SeedBoxRole, existing: string | null): DevboxMergeResult {
  const pristine = renderDevboxJson(role)
  if (existing === null) return { content: pristine, shouldWrite: true }

  let parsed: unknown
  try {
    parsed = JSON.parse(existing)
  } catch {
    return { content: pristine, shouldWrite: true }
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return { content: pristine, shouldWrite: true }
  }

  const packages = (parsed as Record<string, unknown>).packages
  if (!isPackageList(packages) && !isPackageMap(packages)) {
    return { content: pristine, shouldWrite: true }
  }

  const document = parsed as DevboxDocument
  const { packages: current, replaced } = replaceSupersededSpecs(role, packages)
  const existingBases = new Set((Array.isArray(current) ? current : Object.keys(current)).map(packageBaseName))
  const missing = packagesForRole(role).filter((pkg) => !existingBases.has(packageBaseName(pkg)))
  if (missing.length === 0 && !replaced) return { content: existing, shouldWrite: false }

  const mergedPackages: DevboxPackageList | DevboxPackageMap = Array.isArray(current)
    ? [...current, ...missing]
    : { ...current, ...Object.fromEntries(missing.map(splitPackageSpec)) }

  return {
    content: `${JSON.stringify({ ...document, packages: mergedPackages }, null, 2)}\n`,
    shouldWrite: true,
  }
}

async function readOptionalDevboxJson(client: SandboxClient, jsonPath: string): Promise<string | null> {
  try {
    const res = await client.read({ path: jsonPath })
    return Buffer.from(res.content, 'base64').toString('utf8')
  } catch (err) {
    if (err instanceof SandboxHttpError && err.status === 404) return null
    throw err
  }
}

function toBase64(content: string): string {
  return Buffer.from(content, 'utf8').toString('base64')
}

/** Single-quote a path for safe interpolation into a remote shell command. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/** Read the seed marker; returns its trimmed content, or null when absent/unreadable. */
async function readMarker(client: SandboxClient, markerPath: string): Promise<string | null> {
  try {
    const res = await client.read({ path: markerPath })
    return Buffer.from(res.content, 'base64').toString('utf8').trim()
  } catch {
    // 404 (never seeded) or any read error → treat as "no marker" and (re)seed.
    return null
  }
}

/**
 * The exact, stable status line `devbox install` prints (to stderr) immediately
 * BEFORE the actual nix fetch/build/link work — jetify-com/devbox
 * `internal/devbox/packages.go`'s `installPackages`. Everything before this
 * point (`internal/devbox/packages.go`'s `ensureStateIsUpToDate`: devbox.json
 * parse + `@latest` version resolution against devbox's Nixhub search service)
 * is "resolve" — NETWORK-bound even when the local `/nix/store` is already warm
 * (see https://www.jetify.com/blog/how-we-sped-up-nix-package-installs-in-devbox).
 * Everything from here to the command's exit is "realize" (the actual
 * fetch-from-cache/build/link into the box's nix profile).
 *
 * This is a best-effort, source-verified marker, not a devbox API contract: a
 * devbox version whose wording differs simply never matches, and the whole
 * duration lands in `devbox-resolve` with `devbox-realize` absent — never a
 * silently WRONG split (see {@link runDevboxInstall}).
 */
const REALIZE_MARKER = 'Installing the following packages to the nix store'

/**
 * Run `devbox install` to completion, splitting its single opaque bash call
 * into `devbox-resolve` / `devbox-realize` BoxStepTimings using ONLY Core's own
 * clock — never a remote timestamp (see box-timing.ts's clock-authority doc).
 * The command includes bounded post-install cache maintenance. We time WHEN CORE
 * OBSERVES each streamed chunk arrive and note the first arrival whose
 * accumulated text contains {@link REALIZE_MARKER}.
 *
 * Reject on stream error or non-zero exit — unchanged from the prior `runBash`
 * behavior (see its retained doc below). A stream that ends WITHOUT ever
 * delivering an exit code is treated as a FAILURE (not success): the server
 * sends an explicit exit code on every path (including timeout/spawn-failure),
 * so a missing code means the stream was truncated or the server regressed —
 * defaulting it to 0 would silently mark a failed install as done. See
 * packages/k8s-sandbox/src/services/bash.ts.
 */
function runDevboxInstall(
  client: SandboxClient,
  command: string,
  invocationId: string,
  timeoutSeconds: number,
  now: () => number
): Promise<BoxStepTimings> {
  return new Promise((resolve, reject) => {
    const t0 = now()
    let realizeStartedAt: number | null = null
    let scanBuffer = ''
    let exitCode: number | undefined
    let errText = ''
    const stream = client.bash({ command, invocationId, timeoutSeconds })
    stream.on('data', (r: BashResponse) => {
      // Stamp EVERY chunk's arrival (Core's own clock) so the first arrival
      // that carries the marker is timestamped precisely, without adding any
      // conditional branching around when `now()` gets called.
      const arrivedAt = now()
      if (r.error) errText = r.error
      if (r.stderr) {
        const text = Buffer.from(r.stderr, 'base64').toString()
        errText += text
        scanBuffer += text
      }
      if (r.stdout) scanBuffer += Buffer.from(r.stdout, 'base64').toString()
      if (realizeStartedAt === null && scanBuffer.includes(REALIZE_MARKER)) realizeStartedAt = arrivedAt
      if (r.exitCode !== undefined) exitCode = r.exitCode
    })
    stream.on('error', (err: Error) => reject(err))
    stream.on('end', () => {
      const end = now()
      if (exitCode === undefined) {
        reject(new Error(`\`${command}\` ended without an exit code${errText ? `: ${errText.trim()}` : ''}`))
        return
      }
      if (exitCode !== 0) {
        reject(new Error(`\`${command}\` failed (exit ${exitCode})${errText ? `: ${errText.trim()}` : ''}`))
        return
      }
      resolve(
        realizeStartedAt !== null
          ? { 'devbox-resolve': realizeStartedAt - t0, 'devbox-realize': end - realizeStartedAt }
          : { 'devbox-resolve': end - t0 }
      )
    })
  })
}

/**
 * Best-effort devbox.lock cache lookup — NEVER throws. A failure (or a miss)
 * is indistinguishable to the caller: both return `null`, treated as "seed
 * from the network as usual."
 */
async function tryCacheGet(
  cacheGet: (seedHash: string) => Promise<string | null>,
  hash: string
): Promise<string | null> {
  try {
    return await cacheGet(hash)
  } catch (err) {
    log.warn(`devbox lock cache read failed for ${hash} — falling back to network resolve`, err)
    return null
  }
}

/** Best-effort devbox.lock cache store — NEVER throws. */
async function tryCachePut(
  cachePut: (seedHash: string, lockContent: string) => Promise<void>,
  hash: string,
  lockContent: string
): Promise<void> {
  try {
    await cachePut(hash, lockContent)
  } catch (err) {
    log.warn(`devbox lock cache write failed for ${hash} — later boxes will re-resolve over the network`, err)
  }
}

/**
 * Seed the box's per-user devbox comfort set and realize it via `devbox install`.
 *
 * Idempotent through the `~/.tau/devbox/.seeded` hash marker (see file header).
 * THROWS on write/install failure — the caller (VmSandboxManager) treats seeding
 * as NON-fatal and continues the ensure with a degraded shell.
 *
 * When the devbox.json about to be installed is the EXACT pristine role render
 * (no user customization merged in — see the module doc's devbox.lock cache
 * section), a cached `devbox.lock` is seeded into the box before install (cache
 * hit) or the install's generated lock is captured and cached afterward (cache
 * miss). Every cache interaction is best-effort ({@link tryCacheGet} /
 * {@link tryCachePut}) — it can only ever make a box's install faster, never
 * fail or delay the seed.
 *
 * Returns a {@link BoxStepTimings} breakdown for the box-creation summary line
 * (see box-timing.ts): `{}` when the marker skip fires (no install ran — see
 * the module doc's idempotency note), else `devbox-resolve` (+ `devbox-realize`
 * when {@link runDevboxInstall}'s marker was observed).
 */
export async function seedBoxDevbox(
  client: SandboxClient,
  sandboxId: string,
  role: SeedBoxRole,
  deps: SeedBoxDevboxDeps = {},
  invocationIdOverride?: string
): Promise<BoxStepTimings> {
  const home = (deps.boxHome ?? defaultBoxHome)(sandboxId)
  const devboxDir = `${home}/.tau/devbox`
  const jsonPath = `${devboxDir}/devbox.json`
  const lockPath = `${devboxDir}/devbox.lock`
  const markerPath = `${devboxDir}/.seeded`
  const installTimeoutSeconds = deps.installTimeoutSeconds ?? DEFAULT_INSTALL_TIMEOUT_SECONDS
  const now = deps.now ?? Date.now
  const cacheGet = deps.cacheGet ?? DevboxLockCache.get
  const cachePut = deps.cachePut ?? DevboxLockCache.storeIfAbsent

  const hash = computeDevboxSeedHash(role)

  // Skip the slow install when the marker already records THIS exact comfort set.
  const marker = await readMarker(client, markerPath)
  if (marker === hash) return {}

  const existing = await readOptionalDevboxJson(client, jsonPath)
  const merged = mergeDevboxJson(role, existing)
  if (merged.shouldWrite) {
    // Server writes AS THE BOX USER — the box user owns ~/.tau.
    await client.write({ path: jsonPath, content: toBase64(merged.content), createDirs: true })
  }

  // Only trust the devbox.lock cache when the devbox.json is EXACTLY the
  // pristine role render — a user-customized devbox.json's resolution isn't
  // guaranteed to match the pristine set's, so it must never read or write
  // the cache (see the module doc's devbox.lock cache section).
  const isPristine = merged.content === renderDevboxJson(role)

  let cacheHit = false
  if (isPristine) {
    const cachedLock = await tryCacheGet(cacheGet, hash)
    if (cachedLock !== null) {
      try {
        await client.write({ path: lockPath, content: toBase64(cachedLock), createDirs: true })
        cacheHit = true
      } catch (err) {
        log.warn(`writing cached devbox.lock failed for ${hash} — falling back to network resolve`, err)
      }
    }
  }

  // Realize the comfort set. `devbox install` reads devbox.json from its cwd; runs
  // as the box user (the sandbox-server's bash), never root — no sudo here.
  const installCommand = devboxInstallCommand(devboxDir)
  const invocationId = invocationIdOverride ?? computeDevboxInstallInvocationId(sandboxId, role)
  const timings = await runDevboxInstall(client, installCommand, invocationId, installTimeoutSeconds, now)

  // Cache miss + successful install: capture the freshly resolved lock so the
  // NEXT box with this exact comfort set can skip the network resolve.
  if (isPristine && !cacheHit) {
    try {
      const lockRes = await client.read({ path: lockPath })
      const lockContent = Buffer.from(lockRes.content, 'base64').toString('utf8')
      // Guard against caching an empty/blank read-back (e.g. a truncated or
      // not-yet-flushed file) — an empty lock would be worse than no cache
      // entry at all, since it would seed nothing useful into every later box.
      if (lockContent.trim()) {
        await tryCachePut(cachePut, hash, lockContent)
      }
    } catch (err) {
      log.warn(`reading generated devbox.lock failed for ${hash} — not caching`, err)
    }
  }

  // Mark seeded ONLY after a successful install, so a failed install retries next ensure.
  await client.write({ path: markerPath, content: toBase64(hash), createDirs: true })

  return timings
}
