import '../line/motion.css'
import './theme.css'
import type { FarmSkin } from '../types'
import {
  LineAvatar,
  LineBadge,
  LineCompost,
  LineCrates,
  LineDecor,
  LineDefs,
  LineFarmhouse,
  LineGround,
  LineHut,
  LineMailbox,
  LinePlant,
  LinePerson,
  LineRack,
  LinePlot,
  LineRobot,
  LineSeedShed,
  LineSign,
  LineStand,
  LineYard,
} from '../line/sprites'

/** Minimal and futuristic: an endless line grid, line-art plants and floating orbs, in three colours. */
export const futuristSkin: FarmSkin = {
  id: 'futurist',
  label: 'Futurist',
  className: 'g-skin-futurist',
  Defs: LineDefs,
  Ground: LineGround,
  YardBack: LineYard,
  yardFront: () => [],
  Sign: LineSign,
  PlotGround: LinePlot,
  Plant: LinePlant,
  Badge: LineBadge,
  badgeLift: (plot) => (plot.state === 'review' ? -40 : -34),
  Robot: LineRobot,
  Person: LinePerson,
  Avatar: LineAvatar,
  avatarViewBox: '-20 -20 40 40',
  Hut: LineHut,
  Rack: LineRack,
  Stand: LineStand,
  Farmhouse: LineFarmhouse,
  SeedShed: LineSeedShed,
  Mailbox: LineMailbox,
  Crates: LineCrates,
  Compost: LineCompost,
  Decor: LineDecor,
  boxes: {
    robot: [-18, -46, 36, 52],
    person: [-14, -44, 28, 48],
    plant: [-26, -44, 52, 56],
    sign: [-10, -36, 140, 42],
    hut: [-44, -48, 88, 64],
    rack: [-26, -60, 52, 80],
    stand: [-40, -50, 80, 66],
    farmhouse: [-90, -110, 180, 140],
    seedShed: [-54, -70, 108, 90],
    mailbox: [-24, -60, 48, 70],
    crates: [-40, -30, 80, 44],
    compost: [-30, -26, 60, 38],
  },
  worldPad: { top: 80, side: 40, bottom: 30 },
}
